- platform: template
  switches:
    airing_cupboard_fan_switch:
      friendly_name: Airing Cupboard Fan Switch
      value_template: "{{ is_state('input_boolean.airing_cupboard_fan_helper', 'on') }}"
      turn_on:
        action: input_boolean.turn_on
        target:
          entity_id: input_boolean.airing_cupboard_fan_helper
      turn_off:
        action: input_boolean.turn_off
        target:
          entity_id: input_boolean.airing_cupboard_fan_helper
    bathroom_fan_switch:
      friendly_name: Bathroom Fan Switch
      value_template: "{{ is_state('input_boolean.bathroom_fan_helper', 'on') }}"
      turn_on:
        action: input_boolean.turn_on
        target:
          entity_id: input_boolean.bathroom_fan_helper
      turn_off:
        action: input_boolean.turn_off
        target:
          entity_id: input_boolean.bathroom_fan_helper
    garage_fan_switch:
      friendly_name: Garage Fan Switch
      value_template: "{{ is_state('input_boolean.garage_fan_helper', 'on') }}"
      turn_on:
        action: input_boolean.turn_on
        target:
          entity_id: input_boolean.garage_fan_helper
      turn_off:
        action: input_boolean.turn_off
        target:
          entity_id: input_boolean.garage_fan_helper
