esphome:
  name: c3test
  friendly_name: C3Test

esp32:
  board: esp32-c3-devkitm-1
  framework:
    type: esp-idf

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "PNtQH+JEAmKL9dNPSFlj2KG8sFQZnE4SRdp6+glCIJo="

ota:
  - platform: esphome
    password: "7c8d18d7bd82c4379ee957fa09839ba7"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: c3test.anthome.uk

esp32_ble_tracker:
  scan_parameters:
    active: true

bluetooth_proxy:
  active: true

output:
  - platform: ledc
    pin: GPIO2
    frequency: 25000 Hz
    id: fan_pwm

switch:
  - platform: gpio
    pin: GPIO3
    internal: true
    id: fan_relay

fan:
  - platform: speed
    output: fan_pwm
    name: "Exhaust Fan"
    on_turn_on:
      - switch.turn_on: fan_relay
    
    on_turn_off:
      - switch.turn_off: fan_relay